tupValLs = [[doors,[[doorid,[]],[doorlenghtab,[]],[doorlenghtad,[]],[doorcolour,[]],],],
[containerconcretetypes,[[containerconcretetypeid,[]],[containerlengthab,[]],[containerlengthad,[]],[containerlengthae,[]],[containerthickness,[]],[userobjectcommentglobal,[]],],],
[door_wall,[[wallid,[]],[doorid,[]],[displacementab,[]],[displacementad,[]],[orientation,[]],],],
[unit_list,[[unit_id,[]],[unit_name,[]],[unit_abbr,[]],[physicalentityid,[]],[multiplication_factor,[]],],],
[walls,[[wallid,['saurbah', 'saudsadasd', 'sdasdasdadasd', ]],[walllenghtab,['1', '1', '1', ]],[walllenghtad,['1', '1', '1', ]],[wallcolour,['aasd', 'aasd', 'aasd', ]],[userwallcomment,['dasda', 'dasda', 'dasda', ]],],],
[containerconcretetypefaces,[[containerconcretetypeid,[]],[containerconcreteroof,[]],[containerconcretefloor,[]],[containerconcreteright,[]],[containerconcreteleft,[]],[containerconcretefront,[]],[containerconcreteback,[]],],],
[noncontainerconcretetypefaces,[[noncontainerconcretetypeid,[]],[noncontainerconcreteroof,[]],[noncontainerconcretefloor,[]],[noncontainerconcreteright,[]],[noncontainerconcreteleft,[]],[noncontainerconcretefront,[]],[noncontainerconcreteback,[]],],],
[physicalentities,[[physicalentityid,[]],[entity_name,[]],],],
[noncontainerconcretetypes,[[noncontainerconcretetypeid,[]],[noncontainerlengthab,[]],[noncontainerlengthad,[]],[noncontainerlengthae,[]],[userobjectcommentglobal,[]],],],
[propertytypes,[[propertytype,[]],[physicalentityid,[]],[userdescription,[]],],],
[properties,[[propertyid,[]],[propertytype,[]],[userdescription,[]],],],
[containerconcretetypeproperties,[[containerconcretetypeid,[]],[propertyid,[]],[propertyvalue,[]],[measurementunitid,[]],[usercommentglobal,[]],],],
[containerobjects,[[objectid,[]],[containerconcretetypeid,[]],[userlabel,[]],[userobjectcommentlocal,[]],],],
[typeinheritance,[[type_id,[]],[super_type_id,[]],],],
[types,[[type_id,[]],[type_name,[]],[userdescription,[]],],],
[measurementunits,[[measurementunitid,[]],],],
[noncontainerconcretetypeproperties,[[noncontainerconcretetypeid,[]],[propertyid,[]],[propertyvalue,[]],[measurementunitid,[]],[usercommentglobal,[]],],],
[objects,[[objectid,[]],],],
[containerobjectproperties,[[objectid,[]],[userassignedid,[]],[propertyid,[]],[propertyvalue,[]],[usercommentlocal,[]],[userlabel,[]],],],
[noncontainerobjects,[[objectid,[]],[noncontainerconcretetypeid,[]],[userlabel,[]],[userobjectcommentlocal,[]],],],
[noncontainerobjectproperties,[[objectid,[]],[userassignedid,[]],[propertyid,[]],[propertyvalue,[]],[usercommentlocal,[]],[userlabel,[]],],],
[child_parrent,[[childid,[]],[parrentid,[]],[displacementab,[]],[displacementad,[]],[displacementae,[]],[orientation_frontface,[]],[orientation_roofface,[]],],],
]
